Initial draft for specificationa
reactive-streams/reactive-streams-js pull request #5
Opened 2019-01-17 00:12 UTC by OlegDokuka

This PR provides an initial draft of the Reactive Streams Specification for JavaScript.

At the point, the following PR is aimed to amend the specification and after that provide work for actual implementation of Spec and TCK.

2019-01-17 00:14 UTC, OlegDokuka commented
cc/ @viktorklang @kbahr @hypothete @rdegnan

2019-01-18 04:28 UTC, benlesh requested changes

2019-01-18 04:28 UTC, benlesh commented on CONTRIBUTING.md
> +* Netflix Inc., currently represented by Ben Christensen (@benjchristensen)
@benjchristensen is at Facebook now. Perhaps you want @yunong?

2019-01-18 04:28 UTC, benlesh commented on CONTRIBUTING.md
> +# Contributing to the Reactive Streams Project
Add an appropriate code of conduct and link it prominently at the top of this file and in the README. Everyone should know that by interacting and contributing here they are agreeing to abide by the code of conduct. [Contributor Covenant](https://github.com/ContributorCovenant/contributor_covenant) is a widely used one. Not having a code of conduct will actually result in excluding people, which isn't what we want in open source.

2019-01-18 04:28 UTC, benlesh commented on CONTRIBUTING.md
> +The aforementioned waiver of copyrights and other rights is represented by the addition of a line to the file [CopyrightWaivers.txt](https://github.com/reactive-streams/reactive-streams-jvm/blob/mast
May want to move the copyright waivers to this repo so it does not get out of sync or moved.

2019-01-18 04:28 UTC, benlesh commented on tck/README.md
> +# Reactive Streams TCK #
- Add link to CONTRIBUTING doc
- Add link to a code of conduct.

2019-01-18 04:48 UTC, OlegDokuka commented on tck/README.md
> +# Reactive Streams TCK #
This just drafted a spec and not aimed to provide everything at once. Im planning to fix TCK readme once we agreed on spec. Then, after first step, going to fix docs. Does it sound good to you?

2019-01-18 04:49 UTC, OlegDokuka commented on CONTRIBUTING.md
> +The aforementioned waiver of copyrights and other rights is represented by the addition of a line to the file [CopyrightWaivers.txt](https://github.com/reactive-streams/reactive-streams-jvm/blob/mast
Ah, right, I moved it, but missed that link. Thanks

2019-01-18 04:50 UTC, OlegDokuka commented on CONTRIBUTING.md
> +# Contributing to the Reactive Streams Project
Mmm, makes sense. Followed RS spec JVM structure while writing everything, but anyway it makes sense 👍

2019-01-18 04:51 UTC, OlegDokuka commented on CONTRIBUTING.md
> +* Netflix Inc., currently represented by Ben Christensen (@benjchristensen)
Good point. @viktorklang should we change it?

2019-01-18 12:09 UTC, OlegDokuka commented on CONTRIBUTING.md
> +The aforementioned waiver of copyrights and other rights is represented by the addition of a line to the file [CopyrightWaivers.txt](https://github.com/reactive-streams/reactive-streams-jvm/blob/mast
fixed

2019-01-18 12:12 UTC, OlegDokuka commented on CONTRIBUTING.md
> +# Contributing to the Reactive Streams Project
done

2019-01-21 11:44 UTC, kbahr commented on CONTRIBUTING.md
> +* Netflix Inc., currently represented by Ben Christensen (@benjchristensen)
@yunong is no longer at Netflix either - I don't believe Netflix has *any* representation for this anymore. We should reach out to their engineering org to confirm. I'll follow up.

2019-02-01 12:38 UTC, viktorklang commented on CONTRIBUTING.md
> +The aforementioned waiver of copyrights and other rights is represented by the addition of a line to the file [CopyrightWaivers.txt](https://github.com/reactive-streams/reactive-streams-jvm/blob/mast
This needs to refer to the project-local CopyrightWaivers.txt

(currently refers to the JVM one) (https://github.com/reactive-streams/reactive-streams-jvm/blob/master/CopyrightWaivers.txt)

2019-02-01 13:24 UTC, OlegDokuka commented on CONTRIBUTING.md
> +The aforementioned waiver of copyrights and other rights is represented by the addition of a line to the file [CopyrightWaivers.txt](https://github.com/reactive-streams/reactive-streams-jvm/blob/mast
fixed

2019-02-01 13:27 UTC, viktorklang commented on CONTRIBUTING.md
> +* Netflix Inc., currently represented by Ben Christensen (@benjchristensen)
I believe that most of that list is inaccurate right now, but let's leave it as is for now.

2019-02-01 13:28 UTC, OlegDokuka commented on CONTRIBUTING.md
> +* Netflix Inc., currently represented by Ben Christensen (@benjchristensen)
Sounds good

2019-02-01 13:29 UTC, viktorklang commented on CONTRIBUTING.md
> +Creating binary artifacts, uploading them to central repositories and declaring these to be an official release of the Reactive Streams project requires the consent of all gatekeepers. The process is
update `reactive-streams` to `reactive-streams-js`

2019-02-01 13:31 UTC, viktorklang commented on README.md
> +| [:bulb:](#1.3 "1.3 explained") | *The intent of this rule is to make it clear that [external synchronization](#term_ext_sync) must be employed if the Publisher intends to send signals from multiple
Missing period after `context`

2019-02-01 13:31 UTC, OlegDokuka commented on CONTRIBUTING.md
> +Creating binary artifacts, uploading them to central repositories and declaring these to be an official release of the Reactive Streams project requires the consent of all gatekeepers. The process is
done

2019-02-01 13:31 UTC, viktorklang commented on README.md
> +| [:bulb:](#2.7 "2.7 explained") | *The intent of this rule is to establish that [external synchronization](#term_ext_sync) must be added if a Subscriber will be using a Subscription concurrently by
Missing period after context.

2019-02-01 13:33 UTC, viktorklang commented on README.md
> +| [:bulb:](#2.11 "2.11 explained") | *The intent of this rule is to establish that it is the responsibility of the Subscriber implementation to make sure that asynchronous processing of its signals a
Missing period after context.

2019-02-01 13:34 UTC, OlegDokuka commented on README.md
> +| [:bulb:](#2.11 "2.11 explained") | *The intent of this rule is to establish that it is the responsibility of the Subscriber implementation to make sure that asynchronous processing of its signals a
fixed

2019-02-01 13:34 UTC, OlegDokuka commented on README.md
> +| [:bulb:](#2.7 "2.7 explained") | *The intent of this rule is to establish that [external synchronization](#term_ext_sync) must be added if a Subscriber will be using a Subscription concurrently by
fixed

2019-02-01 13:34 UTC, OlegDokuka commented on README.md
> +| [:bulb:](#1.3 "1.3 explained") | *The intent of this rule is to make it clear that [external synchronization](#term_ext_sync) must be employed if the Publisher intends to send signals from multiple
fixed

2019-02-01 13:36 UTC, viktorklang commented
@OlegDokuka It's a bit tricky to see the diff between the original README/spec and this one—mai I suggest adding the original first and creating the PR against it so the diff is "accurate"? :-)

2019-02-01 13:37 UTC, OlegDokuka commented
@viktorklang sure thing. Give me a minute

2019-02-01 14:00 UTC, OlegDokuka commented
@viktorklang done

2019-02-01 14:10 UTC, viktorklang commented
@OlegDokuka Perfect! Thank YOU! ^^

2019-02-01 14:18 UTC, viktorklang commented
@reactive-streams/contributors Please have a look if you're interested!

2019-02-01 14:37 UTC, OlegDokuka commented
@viktorklang dont have an access to that

2019-02-01 14:39 UTC, viktorklang commented
@OlegDokuka you should be on @reactive-streams/js-contributors

2019-02-01 15:25 UTC, OlegDokuka commented
# Long.MAX_VALUE in JS

Regarding usage of BigInt in JS. Unfortunately, JS supports only 2^53 as a MAX save the number to increment without losing calculation precision. Therefore, to keep spec binary compatible with other languages, we have to use `BigInt` type which allows doing math up to 10^1000. However, `BigInt` has its own performance penalty. What I measured is that increment of `BigInt` is about 5 times slower than the increment of the plain `Number`. For example, the following naive benchmark for `BigInt`:

```
function benchmark() {
    const startTime = process.hrtime();
    let i = 0n; // here is n notation after digit means BigInt type 

    while (i < 100000000) {
        i = i + 1n;
    }

    console.log(i);

    const endTime = process.hrtime();

    return [(endTime[0] - startTime[0]), endTime[1] - startTime[1]];
}
```

on average results in (on my 2.9 GHz Intel Core i9):

```
[ 4, 472734712 ] 
```

 > where the first number in the array is `Seconds` and the second in is `Nanos`.

In contrast, the same code but for a plain `Number` type on the same machine:

```
function benchmark() {
    const startTime = process.hrtime();
    let i = 0;

    while (i < 100000000) {
        i = i + 1;
    }

    console.log(i);

    const endTime = process.hrtime();

    return [(endTime[0] - startTime[0]), endTime[1] - startTime[1]];
}
```

on average results in:

```
[ 0, 47754006 ]
```
which is about 4~5 times slower.

### From our conversation with @viktorklang on Twitter

What I saw in Reactor Core JS, which was developed by @akarnokd: 

David Karnok, developing reactor-core-js implemented that special signal in JS as this -> https://github.com/reactor/reactor-core-js/blob/master/src/subscriber.js#L50

 
 Viktor Klang
 When is Infinity reached by adding numbers?

11m 10 minutes ago
 Oleh Dokuka
 
 Viktor Klang
 I mean, if a Subscriber requests 1, and the Publisher doesn't publish anything (yet), when does the aggregation of demand reach the value Infinity?

6m 5 minutes ago
Guess more than iterating to Long.MAX_VALUE

the problem in js is that precision of calculation which overflows 2^53 becomes incorrect like the following

 Oleh Dokuka
 ```
> Number.MAX_SAFE_INTEGER + 1000013
9007199255741004
> Number.MAX_SAFE_INTEGER + 1000015
9007199255741006
> Number.MAX_SAFE_INTEGER + 1000016
9007199255741008
```

2019-02-01 16:35 UTC, OlegDokuka commented
Ahh, even though we tried to rely on incorrect `Number` calculation, in case one send us `Long.MAX_VALUE - 1` we will not be able to do the right math. See the following sample -> https://jsbin.com/taqirareso/edit?js,console

2019-02-01 16:37 UTC, rdegnan commented
I would recommend keeping request_n as Number instead of BigInt. I don't see a need to preserve binary compatibility with other languages within a single language reactive streams implementation, that should be in the domain of binary reactive streams network protocols. RSocket for example limits request_n frames to 2^31-1, so it is up to the RSocket implementation to maintain high/low watermarks and hand out request_n frames up to the requested amount.

2019-02-01 19:40 UTC, benlesh approved these changes

2019-02-01 23:19 UTC, OlegDokuka commented
After some thoughts, I concluded and agree with @rdegnan that we could rely on `Infinite` object as a signal for PUSH-only model and use `Number` instead of `BigInt` since it will have never been reached from the perspective of the time taken for incrementing to that `10^1000` value as well as from the JS behavior which prevents incrementing/decrementing for `Number` type after some specific number.

Any thoughts @viktorklang @benlesh?

2019-02-04 19:36 UTC, viktorklang commented
@OlegDokuka Hmmm, if there is to be a bridge between implementations in different languages, think for instance in Graal, then that bridge would have to know to translate between Long.MAX_VALUE and Infinity. Do we htink that is going to be an issue?

2019-02-04 19:56 UTC, OlegDokuka commented
@viktorklang I don't think this should a big deal. I guess if such interop will be somewhen, we can always provide an additional bridge for that which will catch `Infinite` from js and map it to Long.MAX_VALUE and vice versa

2019-02-04 19:59 UTC, viktorklang commented
@OlegDokuka The thing is that such a bridge would have to keep track of cumulative demand which overflows Long.MAX_VALUE too.

2019-02-04 20:14 UTC, OlegDokuka commented
Another option - stick to `Long.MAX_VALUE` and leave details of the implementation for libs vendors. Anyway, using pure `Number,` it will not be possible to accumulate/decrement the requested amount by `one` started from `2^54`.

On the other hand, in real-world scenarios - no-one will request data by `one` up to `Long.MAX_VALUE`. If such happens - either publisher should wait for 300 years (or in case of JS for half of the year) which is less possible ( guess such publisher should be considered as dead and closed by timeout) or size of request should be higher than 1 or 10 or 100, so in such case, if client increment by 1000 and sending speed is 1000 lower than request frequency, then at some point sending model will be considered as pure push model and in that way interop will be achieved

2019-02-04 20:18 UTC, viktorklang commented
@OlegDokuka What happens if someone asks for (Long.MAX_VALUE / 10) 10 times in a row?

2019-02-04 20:22 UTC, OlegDokuka commented
https://jsbin.com/nariqatexe/edit?js,console

that is funny)

2019-02-04 20:30 UTC, OlegDokuka commented
OK, what if we stick to long max value and leave details of the impl for them. For example, in Reactor we skip validaion of negative request and provide some stric subscribe impl which follows all rules it in case given  subscribe is non-reactor ecosysytem one

2019-02-25 22:31 UTC, OlegDokuka commented
@viktorklang provided last fixes to the spec related to the upper limit. Spec keeps clear a requirement of the upper limit equal to `Long.MAX_VALUE`. It does not specify a particular type of solution and does not limit API to `bigint` type. It mentions JS limits and advice vendors to provide appropriate math in order to achieve the right precision in tracking the requested amount.

If it looks good to you, we can merge it and I will send TCK shortly

2019-02-26 08:16 UTC, viktorklang commented
@OlegDokuka Latest commit looks good to me. You might want to check the latest master in reactive-streams-jvm for some updated verbiage, such as: https://github.com/reactive-streams/reactive-streams-jvm/commit/4d6cdb76babbd88c80303115b4d35c4343233da4

Nice work, Oleg!

2019-02-26 17:43 UTC, OlegDokuka commented
Waits resolution for https://github.com/reactive-streams/reactive-streams-jvm/pull/448 so once we have it, amend latest fixes and merge this PR

2019-03-06 09:30 UTC, merged